### ISSUE TITLE
Update docs re ID key

### ISSUE THREAD

**Issue by samwilson** [mkuklis/depot.js#12]
The generated `_id` key is a GUID isn't it? The docs mention that it's an integer.

Also, should the docs refer to `_id` rather than just `id` ([e.g.](https://github.com/mkuklis/depot.js#return-single-record-by-id)) everywhere other than the bit about setting `idAttribute`?

**Comment by samwilson** [comment]
(Thanks for a terrific simple library by the way!)

**Comment by mkuklis** [comment]
@samwilson thank you for pointing these out.
